# Create self-signed code signing certificate and signing.config.js for TeamFocus.
# Run in PowerShell (no Admin required):
#   cd D:\RISOSI\TeamFocus\desktop
#   Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force; .\create-signing-cert.ps1
#
# Or from CMD:
#   powershell -ExecutionPolicy Bypass -File create-signing-cert.ps1

$ErrorActionPreference = "Stop"
$desktopDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$certsDir = Join-Path $desktopDir "certs"
$pfxPath = Join-Path $certsDir "teamfocus-signing.pfx"

# Strong password: 24 chars, mixed case + numbers + symbols
$chars = "abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789!@#$%&*"
$password = -join ((1..24) | ForEach-Object { $chars[(Get-Random -Maximum $chars.Length)] })

if (-not (Test-Path $certsDir)) {
    New-Item -ItemType Directory -Path $certsDir -Force | Out-Null
}

Write-Host "Creating self-signed code signing certificate..."
$cert = New-SelfSignedCertificate `
    -Type CodeSigningCert `
    -Subject "CN=RISOSI" `
    -KeyUsage DigitalSignature `
    -FriendlyName "RISOSI TeamFocus Code Signing" `
    -CertStoreLocation "Cert:\CurrentUser\My" `
    -NotAfter (Get-Date).AddYears(3)

$secPassword = ConvertTo-SecureString -String $password -Force -AsPlainText
Export-PfxCertificate -Cert $cert -FilePath $pfxPath -Password $secPassword | Out-Null
Remove-Item -Path "Cert:\CurrentUser\My\$($cert.Thumbprint)" -Force -ErrorAction SilentlyContinue

# signing.config.js - escape password for JS string (backslash and quote)
$passEscaped = $password -replace '\\', '\\\\' -replace '"', '\"'
$configContent = @"
/**
 * Generated by create-signing-cert.ps1 - do not commit (gitignored).
 */
const path = require("path");
module.exports = {
  winCertificateFile: path.join(__dirname, "certs", "teamfocus-signing.pfx"),
  winCertificatePassword: "$passEscaped",
  appleId: undefined,
  appleTeamId: undefined,
  appleAppSpecificPassword: undefined,
};
"@

[System.IO.File]::WriteAllText((Join-Path $desktopDir "signing.config.js"), $configContent)

Write-Host ""
Write-Host "Done. Certificate and config created."
Write-Host "  PFX:  $pfxPath"
Write-Host "  Config: $desktopDir\signing.config.js"
Write-Host ""
Write-Host "Password (save it if you need to reuse the cert): $password"
Write-Host ""
Write-Host "Next: run   yarn make   to build a signed installer."
Write-Host "Note: Self-signed certs may still show a SmartScreen warning; a purchased cert reduces or removes it."
