/**
 * Generated by create-signing-cert.ps1 - do not commit (gitignored).
 */
const path = require("path");
module.exports = {
  winCertificateFile: path.join(__dirname, "certs", "teamfocus-signing.pfx"),
  winCertificatePassword: "r!sY5QR9t$BQBcgqG6ztL334",
  appleId: undefined,
  appleTeamId: undefined,
  appleAppSpecificPassword: undefined,
};